services:
  mysql:
    image: mysql:8.0
    container_name: med_databse
    environment:
      MYSQL_ROOT_PASSWORD: med_mdp_root
      MYSQL_DATABASE: med_db
      MYSQL_USER: med_user
      MYSQL_PASSWORD: med_user_password
    ports:
        - "3307:3306"
    volumes:
      - mysql_data:/var/lib/mysql
    networks:
      - med_network

volumes:
  mysql_data: {}

networks:
    med_network:
        driver: bridge